title: Sanjyot Agureddy # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior DotNet Developer
  <br><br>
  <img src="/GitHub.png" width="16"/> <a href="mailto:sanjyot.agureddy4@gmail.com">sanjyot.agureddy4@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/sanjyotagureddy/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/sanjyotagureddy/">GitHub</a>
theme: jekyll-theme-minimal
